# Twitter configuration
# More info on how to register the application at http://dev.twitter.com

consumer_key:    om0AvElOnmtjAmBmjUmkg
consumer_secret: ctVq0hN3zYyc90t6ZX7LidAp9RkNeqAwPOrWaPuteE
oauth_token:        241596263-34CuJsLeexQOZlWMPkwJXjEEU0Ij9Z4ALUN9gRqG
oauth_token_secret: fpJ1egXcGfq2gdiwM1GebRCQOA5eh4lr9XOO416eOo


# Mongo configuration

host:     localhost
port:     27017
database: twittermometro_development

# database: mongodb://twitteruser:demopass@ds039467.mongolab.com:39467/twitter
# mongo ds039467.mongolab.com:39467/twitter -u twitteruser -p demopass
# mongo_uri: mongodb://twitteruser:demopass@ds039467.mongolab.com:39467
# db_name: twitter