require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CorpusPositivesController do

  # This should return the minimal set of attributes required to create a valid
  # CorpusPositive. As you add validations to CorpusPositive, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "sentence" => "MyText" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CorpusPositivesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all corpus_positives as @corpus_positives" do
      corpus_positive = CorpusPositive.create! valid_attributes
      get :index, {}, valid_session
      assigns(:corpus_positives).should eq([corpus_positive])
    end
  end

  describe "GET show" do
    it "assigns the requested corpus_positive as @corpus_positive" do
      corpus_positive = CorpusPositive.create! valid_attributes
      get :show, {:id => corpus_positive.to_param}, valid_session
      assigns(:corpus_positive).should eq(corpus_positive)
    end
  end

  describe "GET new" do
    it "assigns a new corpus_positive as @corpus_positive" do
      get :new, {}, valid_session
      assigns(:corpus_positive).should be_a_new(CorpusPositive)
    end
  end

  describe "GET edit" do
    it "assigns the requested corpus_positive as @corpus_positive" do
      corpus_positive = CorpusPositive.create! valid_attributes
      get :edit, {:id => corpus_positive.to_param}, valid_session
      assigns(:corpus_positive).should eq(corpus_positive)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CorpusPositive" do
        expect {
          post :create, {:corpus_positive => valid_attributes}, valid_session
        }.to change(CorpusPositive, :count).by(1)
      end

      it "assigns a newly created corpus_positive as @corpus_positive" do
        post :create, {:corpus_positive => valid_attributes}, valid_session
        assigns(:corpus_positive).should be_a(CorpusPositive)
        assigns(:corpus_positive).should be_persisted
      end

      it "redirects to the created corpus_positive" do
        post :create, {:corpus_positive => valid_attributes}, valid_session
        response.should redirect_to(CorpusPositive.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved corpus_positive as @corpus_positive" do
        # Trigger the behavior that occurs when invalid params are submitted
        CorpusPositive.any_instance.stub(:save).and_return(false)
        post :create, {:corpus_positive => { "sentence" => "invalid value" }}, valid_session
        assigns(:corpus_positive).should be_a_new(CorpusPositive)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CorpusPositive.any_instance.stub(:save).and_return(false)
        post :create, {:corpus_positive => { "sentence" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested corpus_positive" do
        corpus_positive = CorpusPositive.create! valid_attributes
        # Assuming there are no other corpus_positives in the database, this
        # specifies that the CorpusPositive created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CorpusPositive.any_instance.should_receive(:update_attributes).with({ "sentence" => "MyText" })
        put :update, {:id => corpus_positive.to_param, :corpus_positive => { "sentence" => "MyText" }}, valid_session
      end

      it "assigns the requested corpus_positive as @corpus_positive" do
        corpus_positive = CorpusPositive.create! valid_attributes
        put :update, {:id => corpus_positive.to_param, :corpus_positive => valid_attributes}, valid_session
        assigns(:corpus_positive).should eq(corpus_positive)
      end

      it "redirects to the corpus_positive" do
        corpus_positive = CorpusPositive.create! valid_attributes
        put :update, {:id => corpus_positive.to_param, :corpus_positive => valid_attributes}, valid_session
        response.should redirect_to(corpus_positive)
      end
    end

    describe "with invalid params" do
      it "assigns the corpus_positive as @corpus_positive" do
        corpus_positive = CorpusPositive.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CorpusPositive.any_instance.stub(:save).and_return(false)
        put :update, {:id => corpus_positive.to_param, :corpus_positive => { "sentence" => "invalid value" }}, valid_session
        assigns(:corpus_positive).should eq(corpus_positive)
      end

      it "re-renders the 'edit' template" do
        corpus_positive = CorpusPositive.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CorpusPositive.any_instance.stub(:save).and_return(false)
        put :update, {:id => corpus_positive.to_param, :corpus_positive => { "sentence" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested corpus_positive" do
      corpus_positive = CorpusPositive.create! valid_attributes
      expect {
        delete :destroy, {:id => corpus_positive.to_param}, valid_session
      }.to change(CorpusPositive, :count).by(-1)
    end

    it "redirects to the corpus_positives list" do
      corpus_positive = CorpusPositive.create! valid_attributes
      delete :destroy, {:id => corpus_positive.to_param}, valid_session
      response.should redirect_to(corpus_positives_url)
    end
  end

end
